# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# require 'faker'
require 'open-uri'

User.destroy_all
Dispensary.destroy_all

user1 = User.create(username: "mara", email: "mara@mara.com", password: 'maramara')
user2 = User.create(username: "mike", email: "mike@mike.com", password: 'mikemike')
user3 = User.create(username: "veronika", email: "submissive@breedable.com", password: 'exactlyright')
user4 = User.create(username: "guest", email: "guest@email.com", password: 'password')

# east bay
dispensary1 = Dispensary.create(name: "Harborside Oakland", address: "1840 Embarcadero, Oakland, CA 94606", dispensary_type: 'Recreational & Medical', url: 'images/dispensaries/Harborside.png')
dispensary2 = Dispensary.create(name: "Cookies Oakland", address: "1776 Broadway, Oakland, CA 94612", dispensary_type: 'Medical', url: 'images/dispensaries/cookies.jpg')
dispensary3 = Dispensary.create(name: "MedMen - Emeryville", address: "3996 San Pablo Ave, Emeryville, CA 94608", dispensary_type: 'Recreational', url: 'images/dispensaries/medmen.jpg')
dispensary4 = Dispensary.create(name: "High Times Oakport", address: "7817 Oakport St, Oakland, CA 94621", dispensary_type: 'Medical & Recreational', url: 'images/dispensaries/hightimes.jpeg')
dispensary5 = Dispensary.create(name: "Blum - Oakland", address: "578 W Grand Ave, Oakland, CA 94612", dispensary_type: 'Medical & Recreational', url: 'images/dispensaries/blum.jpeg')
dispensary6 = Dispensary.create(name: "Embarc Alameda", address: "1616 Webster St, Alameda, CA 94501", dispensary_type: 'Recreational', url: 'images/dispensaries/embarc.jpg')
dispensary7 = Dispensary.create(name: "STIIIZY UNION SQUARE", address: "180 O'Farrell St, San Francisco, CA 94102", dispensary_type: 'Recreational & Medical', url: 'images/dispensaries/stiiizy.jpg')
dispensary8 = Dispensary.create(name: "Fig & Thistle Apothecary", address: "313 Ivy St, San Francisco, CA 94102", dispensary_type: 'Recreational', url: 'images/dispensaries/figthistle.jpeg')
dispensary9 = Dispensary.create(name: "Eureka Sky", address: "3989 17th St, San Francisco, CA 94114", dispensary_type: 'Recreational', url: 'images/dispensaries/eurekasky.jpg')
dispensary10 = Dispensary.create(name: "Authentic 415", address: "165 Mississippi St, San Francisco, CA 94107", dispensary_type: 'Medical & Recreational', url: 'images/dispensaries/authentic415.jpeg')
dispensary11 = Dispensary.create(name: "The Apothecarium - Marina", address: "2414 Lombard St, San Francisco, CA 94123", dispensary_type: 'Recreational', url: 'images/dispensaries/apothecarium.jpg')
dispensary12 = Dispensary.create(name: "CBCB", address: "Cannabis Buyers' Club of Berkeley, 3033 Shattuck Ave, Berkeley, CA 94705", dispensary_type: 'Medical & Recreational', url: 'images/dispensaries/cbcb.jpg')


harborside = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/Harborside.png')
dispensary1.photo.attach(io: harborside, filename: 'Harborside.png')
cookies = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/cookies.jpg')
dispensary2.photo.attach(io: cookies, filename: 'cookies.jpg')
medmen = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/medmen.jpg')
dispensary3.photo.attach(io: medmen, filename: 'medmen.jpg')
hightimes = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/hightimes.jpeg')
dispensary4.photo.attach(io: hightimes, filename: 'hightimes.jpeg')
blum = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/blum.jpeg')
dispensary5.photo.attach(io: blum, filename: 'blum.jpeg')
embarc = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/embarc.jpg')
dispensary6.photo.attach(io: embarc, filename: 'embarc.jpg')
stiiizy = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/stiiizy.jpg')
dispensary7.photo.attach(io: stiiizy, filename: 'stiiizy.jpg')
figthistle = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/figthistle.jpeg')
dispensary8.photo.attach(io: figthistle, filename: 'figthistle.jpeg')
eurekasky = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/eurekasky.jpg')
dispensary9.photo.attach(io: eurekasky, filename: 'eurekasky.jpg')
authentic415 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/authentic415.jpeg')
dispensary10.photo.attach(io: authentic415, filename: 'authentic415.jpeg')
apothecarium = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/apothecarium.jpg')
dispensary11.photo.attach(io: apothecarium, filename: 'apothecarium.jpg')
cbcb = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/dispensaries/cbcb.jpg')
dispensary12.photo.attach(io: cbcb, filename: 'cbcb.jpg')

order1 = Order.create(user_id: 1, dispensary_id: 1, product_id: 1, purchase_num: 420, quantity: 1)
order2 = Order.create(user_id: 1, dispensary_id: 1, product_id: 1, purchase_num: 421, quantity: 1)
order3 = Order.create(user_id: 1, dispensary_id: 1, product_id: 1, purchase_num: 422, quantity: 1)
order4 = Order.create(user_id: 1, dispensary_id: 1, product_id: 1, purchase_num: 423, quantity: 1)

productA1 = Product.create(dispensary_id: 1, name: "Ice Cream Cake", brand: "Humboldt's Finest", price: 120.00, category: "Flower", size: "per 1/2 oz", url: 'images/products/icc.png')
productA2 = Product.create(dispensary_id: 1, name: "Sour Watermelon Fruit Chews", brand: "Smokiez Edibles", price: 16.00, category: "Edibles", size: "10 pieces per package", url: 'images/products/smokiez.png')
productA3 = Product.create(dispensary_id: 1, name: "The Remedy", brand: "Mary's Medicinals", price: 50.00, category: "Tincture", size: "60 servings in a 15mL bottle", url: 'images/products/theremedy.png')
productA4 = Product.create(dispensary_id: 1, name: "Full Mind - Strawberry", brand: "Nuvata", price: 40.00, category: "Disposable Vape Pen", size: "per 1/2 g", url: 'images/products/Nuvata.png')
productA5 = Product.create(dispensary_id: 1, name: "Original Glue #4", brand: "Select Elite", price: 30.00, category: "Cartridge", size: "per 1/2 g", url: 'images/products/SelectElite.png')
productA6 = Product.create(dispensary_id: 1, name: "Releaf Balm 3:1 CBD:THC 600mg", brand: "Papa & Barkley", price: 90.00, category: "Balms & Salves", size: "15mL", url: 'images/products/Releaf.png')

productB1 = Product.create(dispensary_id: 2, name: "Gelonade", brand: "Connected Cannabis Co.", price: 18.00, category: "Pre-Roll", size: "1g", url: 'images/products/gelonade.png')
productB2 = Product.create(dispensary_id: 2, name: "Animas Valley", brand: "Raw Garden", price: 35.00, category: "Live Resin", size: "per 1 g", url: 'images/products/AnimasValleyLiveResin.png')
productB3 = Product.create(dispensary_id: 2, name: "Pink Lemonade", brand: "Kanha", price: 14.00, category: "Gummies", size: "10 pieces x 10mg/gummy", url: 'images/products/kanha.png')
productB4 = Product.create(dispensary_id: 2, name: "Banana OG", brand: "Apothecary Genetics", price: 30.00, category: "Shatter", size: "per 1 g", url: 'images/products/KingsGardenBananaOG.png')
productB5 = Product.create(dispensary_id: 2, name: "Dark Heart Nursery", brand: "Knights Templar", price: 16.00, category: "Clone", size: "each", url: 'images/products/KnightsTemplar.png')
productB6 = Product.create(dispensary_id: 2, name: "Calm 101", brand: "Canndescent", price: 60.00, category: "Flower", size: "per 1/8 oz", url: 'images/products/Canndescent.png')

icc = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/icc.png')
productA1.photo.attach(io: icc, filename: 'icc.png')
smokiez = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/smokiez.png')
productA2.photo.attach(io: smokiez, filename: 'smokiez.png')
theremedy = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/theremedy.png')
productA3.photo.attach(io: theremedy, filename: 'theremedy.png')
Nuvata = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Nuvata.png')
productA4.photo.attach(io: Nuvata, filename: 'Nuvata.png')
SelectElite = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/SelectElite.png')
productA5.photo.attach(io: SelectElite, filename: 'SelectElite.png')
Releaf = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Releaf.png')
productA6.photo.attach(io: Releaf, filename: 'Releaf.png')
gelonade = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/gelonade.png')
productB1.photo.attach(io: gelonade, filename: 'gelonade.png')
AnimasValleyLiveResin = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/AnimasValleyLiveResin.png')
productB2.photo.attach(io: AnimasValleyLiveResin, filename: 'AnimasValleyLiveResin.png')
kanha = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/kanha.png')
productB3.photo.attach(io: kanha, filename: 'kanha.png')
KingsGardenBananaOG = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KingsGardenBananaOG.png')
productB4.photo.attach(io: KingsGardenBananaOG, filename: 'KingsGardenBananaOG.png')
KnightsTemplar = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KnightsTemplar.png')
productB5.photo.attach(io: KnightsTemplar, filename: 'KnightsTemplar.png')
Canndescent = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Canndescent.png')
productB6.photo.attach(io: Canndescent, filename: 'Canndescent.png')

productC1 = Product.create(dispensary_id: 3, name: "Sour Watermelon Fruit Chews", brand: "Smokiez Edibles", price: 16.00, category: "Edibles", size: "10 pieces per package", url: 'images/products/smokiez.png')
productC2 = Product.create(dispensary_id: 3, name: "The Remedy", brand: "Mary's Medicinals", price: 50.00, category: "Tincture", size: "60 servings in a 15mL bottle", url: 'images/products/theremedy.png')
productC3 = Product.create(dispensary_id: 3, name: "Full Mind - Strawberry", brand: "Nuvata", price: 40.00, category: "Disposable Vape Pen", size: "per 1/2 g", url: 'images/products/Nuvata.png')
productC4 = Product.create(dispensary_id: 3, name: "Original Glue #4", brand: "Select Elite", price: 30.00, category: "Cartridge", size: "per 1/2 g", url: 'images/products/SelectElite.png')
productC5 = Product.create(dispensary_id: 3, name: "Releaf Balm 3:1 CBD:THC 600mg", brand: "Papa & Barkley", price: 90.00, category: "Balms & Salves", size: "15mL", url: 'images/products/Releaf.png')
productC6 = Product.create(dispensary_id: 3, name: "Ice Cream Cake", brand: "Humboldt's Finest", price: 120.00, category: "Flower", size: "per 1/2 oz", url: 'images/products/icc.png')

productD1 = Product.create(dispensary_id: 4, name: "Animas Valley", brand: "Raw Garden", price: 35.00, category: "Live Resin", size: "per 1 g", url: 'images/products/AnimasValleyLiveResin.png')
productD2 = Product.create(dispensary_id: 4, name: "Pink Lemonade", brand: "Kanha", price: 14.00, category: "Gummies", size: "10 pieces x 10mg/gummy", url: 'images/products/kanha.png')
productD3 = Product.create(dispensary_id: 4, name: "Banana OG", brand: "Apothecary Genetics", price: 30.00, category: "Shatter", size: "per 1 g", url: 'images/products/KingsGardenBananaOG.png')
productD4 = Product.create(dispensary_id: 4, name: "Dark Heart Nursery", brand: "Knights Templar", price: 16.00, category: "Clone", size: "each", url: 'images/products/KnightsTemplar.png')
productD5 = Product.create(dispensary_id: 4, name: "Calm 101", brand: "Canndescent", price: 60.00, category: "Flower", size: "per 1/8 oz", url: 'images/products/Canndescent.png')
productD6 = Product.create(dispensary_id: 4, name: "Gelonade", brand: "Connected Cannabis Co.", price: 18.00, category: "Pre-Roll", size: "1g", url: 'images/products/gelonade.png')

smokiez2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/smokiez.png')
productC1.photo.attach(io: smokiez2, filename: 'smokiez.png')
theremedy2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/theremedy.png')
productC2.photo.attach(io: theremedy2, filename: 'theremedy.png')
Nuvata2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Nuvata.png')
productC3.photo.attach(io: Nuvata2, filename: 'Nuvata.png')
SelectElite2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/SelectElite.png')
productC4.photo.attach(io: SelectElite2, filename: 'SelectElite.png')
Releaf2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Releaf.png')
productC5.photo.attach(io: Releaf2, filename: 'Releaf.png')
icc2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/icc.png')
productC6.photo.attach(io: icc2, filename: 'icc.png')

AnimasValleyLiveResin2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/AnimasValleyLiveResin.png')
productD1.photo.attach(io: AnimasValleyLiveResin2, filename: 'AnimasValleyLiveResin.png')
kanha2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/kanha.png')
productD2.photo.attach(io: kanha2, filename: 'kanha.png')
KingsGardenBananaOG2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KingsGardenBananaOG.png')
productD3.photo.attach(io: KingsGardenBananaOG2, filename: 'KingsGardenBananaOG.png')
KnightsTemplar2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KnightsTemplar.png')
productD4.photo.attach(io: KnightsTemplar2, filename: 'KnightsTemplar.png')
Canndescent2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Canndescent.png')
productD5.photo.attach(io: Canndescent2, filename: 'Canndescent.png')
gelonade2 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/gelonade.png')
productD6.photo.attach(io: gelonade2, filename: 'gelonade.png')

productE1 = Product.create(dispensary_id: 5, name: "The Remedy", brand: "Mary's Medicinals", price: 50.00, category: "Tincture", size: "60 servings in a 15mL bottle", url: 'images/products/theremedy.png')
productE2 = Product.create(dispensary_id: 5, name: "Full Mind - Strawberry", brand: "Nuvata", price: 40.00, category: "Disposable Vape Pen", size: "per 1/2 g", url: 'images/products/Nuvata.png')
productE3 = Product.create(dispensary_id: 5, name: "Original Glue #4", brand: "Select Elite", price: 30.00, category: "Cartridge", size: "per 1/2 g", url: 'images/products/SelectElite.png')
productE4 = Product.create(dispensary_id: 5, name: "Releaf Balm 3:1 CBD:THC 600mg", brand: "Papa & Barkley", price: 90.00, category: "Balms & Salves", size: "15mL", url: 'images/products/Releaf.png')
productE5 = Product.create(dispensary_id: 5, name: "Ice Cream Cake", brand: "Humboldt's Finest", price: 120.00, category: "Flower", size: "per 1/2 oz", url: 'images/products/icc.png')
productE6 = Product.create(dispensary_id: 5, name: "Sour Watermelon Fruit Chews", brand: "Smokiez Edibles", price: 16.00, category: "Edibles", size: "10 pieces per package", url: 'images/products/smokiez.png')

productF1 = Product.create(dispensary_id: 6, name: "Pink Lemonade", brand: "Kanha", price: 14.00, category: "Gummies", size: "10 pieces x 10mg/gummy", url: 'images/products/kanha.png')
productF2 = Product.create(dispensary_id: 6, name: "Banana OG", brand: "Apothecary Genetics", price: 30.00, category: "Shatter", size: "per 1 g", url: 'images/products/KingsGardenBananaOG.png')
productF3 = Product.create(dispensary_id: 6, name: "Dark Heart Nursery", brand: "Knights Templar", price: 16.00, category: "Clone", size: "each", url: 'images/products/KnightsTemplar.png')
productF4 = Product.create(dispensary_id: 6, name: "Calm 101", brand: "Canndescent", price: 60.00, category: "Flower", size: "per 1/8 oz", url: 'images/products/Canndescent.png')
productF5 = Product.create(dispensary_id: 6, name: "Gelonade", brand: "Connected Cannabis Co.", price: 18.00, category: "Pre-Roll", size: "1g", url: 'images/products/gelonade.png')
productF6 = Product.create(dispensary_id: 6, name: "Animas Valley", brand: "Raw Garden", price: 35.00, category: "Live Resin", size: "per 1 g", url: 'images/products/AnimasValleyLiveResin.png')

theremedy3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/theremedy.png')
productE1.photo.attach(io: theremedy3, filename: 'theremedy.png')
Nuvata3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Nuvata.png')
productE2.photo.attach(io: Nuvata3, filename: 'Nuvata.png')
SelectElite3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/SelectElite.png')
productE3.photo.attach(io: SelectElite3, filename: 'SelectElite.png')
Releaf3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Releaf.png')
productE4.photo.attach(io: Releaf3, filename: 'Releaf.png')
icc3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/icc.png')
productE5.photo.attach(io: icc3, filename: 'icc.png')
smokiez3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/smokiez.png')
productE6.photo.attach(io: smokiez3, filename: 'smokiez.png')

kanha3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/kanha.png')
productF1.photo.attach(io: kanha3, filename: 'kanha.png')
KingsGardenBananaOG3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KingsGardenBananaOG.png')
productF2.photo.attach(io: KingsGardenBananaOG3, filename: 'KingsGardenBananaOG.png')
KnightsTemplar3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KnightsTemplar.png')
productF3.photo.attach(io: KnightsTemplar3, filename: 'KnightsTemplar.png')
Canndescent3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Canndescent.png')
productF4.photo.attach(io: Canndescent3, filename: 'Canndescent.png')
gelonade3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/gelonade.png')
productF5.photo.attach(io: gelonade3, filename: 'gelonade.png')
AnimasValleyLiveResin3 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/AnimasValleyLiveResin.png')
productF6.photo.attach(io: AnimasValleyLiveResin3, filename: 'AnimasValleyLiveResin.png')

productG1 = Product.create(dispensary_id: 7, name: "Full Mind - Strawberry", brand: "Nuvata", price: 40.00, category: "Disposable Vape Pen", size: "per 1/2 g", url: 'images/products/Nuvata.png')
productG2 = Product.create(dispensary_id: 7, name: "Original Glue #4", brand: "Select Elite", price: 30.00, category: "Cartridge", size: "per 1/2 g", url: 'images/products/SelectElite.png')
productG3 = Product.create(dispensary_id: 7, name: "Releaf Balm 3:1 CBD:THC 600mg", brand: "Papa & Barkley", price: 90.00, category: "Balms & Salves", size: "15mL", url: 'images/products/Releaf.png')
productG4 = Product.create(dispensary_id: 7, name: "Ice Cream Cake", brand: "Humboldt's Finest", price: 120.00, category: "Flower", size: "per 1/2 oz", url: 'images/products/icc.png')
productG5 = Product.create(dispensary_id: 7, name: "Sour Watermelon Fruit Chews", brand: "Smokiez Edibles", price: 16.00, category: "Edibles", size: "10 pieces per package", url: 'images/products/smokiez.png')
productG6 = Product.create(dispensary_id: 7, name: "The Remedy", brand: "Mary's Medicinals", price: 50.00, category: "Tincture", size: "60 servings in a 15mL bottle", url: 'images/products/theremedy.png')

productH1 = Product.create(dispensary_id: 8, name: "Banana OG", brand: "Apothecary Genetics", price: 30.00, category: "Shatter", size: "per 1 g", url: 'images/products/KingsGardenBananaOG.png')
productH2 = Product.create(dispensary_id: 8, name: "Dark Heart Nursery", brand: "Knights Templar", price: 16.00, category: "Clone", size: "each", url: 'images/products/KnightsTemplar.png')
productH3 = Product.create(dispensary_id: 8, name: "Calm 101", brand: "Canndescent", price: 60.00, category: "Flower", size: "per 1/8 oz", url: 'images/products/Canndescent.png')
productH4 = Product.create(dispensary_id: 8, name: "Gelonade", brand: "Connected Cannabis Co.", price: 18.00, category: "Pre-Roll", size: "1g", url: 'images/products/gelonade.png')
productH5 = Product.create(dispensary_id: 8, name: "Animas Valley", brand: "Raw Garden", price: 35.00, category: "Live Resin", size: "per 1 g", url: 'images/products/AnimasValleyLiveResin.png')
productH6 = Product.create(dispensary_id: 8, name: "Pink Lemonade", brand: "Kanha", price: 14.00, category: "Gummies", size: "10 pieces x 10mg/gummy", url: 'images/products/kanha.png')

Nuvata4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Nuvata.png')
productG1.photo.attach(io: Nuvata4, filename: 'Nuvata.png')
SelectElite4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/SelectElite.png')
productG2.photo.attach(io: SelectElite4, filename: 'SelectElite.png')
Releaf4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Releaf.png')
productG3.photo.attach(io: Releaf4, filename: 'Releaf.png')
icc4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/icc.png')
productG4.photo.attach(io: icc4, filename: 'icc.png')
smokiez4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/smokiez.png')
productG5.photo.attach(io: smokiez4, filename: 'smokiez.png')
theremedy4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/theremedy.png')
productG6.photo.attach(io: theremedy4, filename: 'theremedy.png')

KingsGardenBananaOG4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KingsGardenBananaOG.png')
productH1.photo.attach(io: KingsGardenBananaOG4, filename: 'KingsGardenBananaOG.png')
KnightsTemplar4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KnightsTemplar.png')
productH2.photo.attach(io: KnightsTemplar4, filename: 'KnightsTemplar.png')
Canndescent4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Canndescent.png')
productH3.photo.attach(io: Canndescent4, filename: 'Canndescent.png')
gelonade4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/gelonade.png')
productH4.photo.attach(io: gelonade4, filename: 'gelonade.png')
AnimasValleyLiveResin4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/AnimasValleyLiveResin.png')
productH5.photo.attach(io: AnimasValleyLiveResin4, filename: 'AnimasValleyLiveResin.png')
kanha4 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/kanha.png')
productH6.photo.attach(io: kanha4, filename: 'kanha.png')

productI1 = Product.create(dispensary_id: 9, name: "Original Glue #4", brand: "Select Elite", price: 30.00, category: "Cartridge", size: "per 1/2 g", url: 'images/products/SelectElite.png')
productI2 = Product.create(dispensary_id: 9, name: "Releaf Balm 3:1 CBD:THC 600mg", brand: "Papa & Barkley", price: 90.00, category: "Balms & Salves", size: "15mL", url: 'images/products/Releaf.png')
productI3 = Product.create(dispensary_id: 9, name: "Ice Cream Cake", brand: "Humboldt's Finest", price: 120.00, category: "Flower", size: "per 1/2 oz", url: 'images/products/icc.png')
productI4 = Product.create(dispensary_id: 9, name: "Sour Watermelon Fruit Chews", brand: "Smokiez Edibles", price: 16.00, category: "Edibles", size: "10 pieces per package", url: 'images/products/smokiez.png')
productI5 = Product.create(dispensary_id: 9, name: "The Remedy", brand: "Mary's Medicinals", price: 50.00, category: "Tincture", size: "60 servings in a 15mL bottle", url: 'images/products/theremedy.png')
productI6 = Product.create(dispensary_id: 9, name: "Full Mind - Strawberry", brand: "Nuvata", price: 40.00, category: "Disposable Vape Pen", size: "per 1/2 g", url: 'images/products/Nuvata.png')

productJ1 = Product.create(dispensary_id: 10, name: "Dark Heart Nursery", brand: "Knights Templar", price: 16.00, category: "Clone", size: "each", url: 'images/products/KnightsTemplar.png')
productJ2 = Product.create(dispensary_id: 10, name: "Calm 101", brand: "Canndescent", price: 60.00, category: "Flower", size: "per 1/8 oz", url: 'images/products/Canndescent.png')
productJ3 = Product.create(dispensary_id: 10, name: "Gelonade", brand: "Connected Cannabis Co.", price: 18.00, category: "Pre-Roll", size: "1g", url: 'images/products/gelonade.png')
productJ4 = Product.create(dispensary_id: 10, name: "Animas Valley", brand: "Raw Garden", price: 35.00, category: "Live Resin", size: "per 1 g", url: 'images/products/AnimasValleyLiveResin.png')
productJ5 = Product.create(dispensary_id: 10, name: "Pink Lemonade", brand: "Kanha", price: 14.00, category: "Gummies", size: "10 pieces x 10mg/gummy", url: 'images/products/kanha.png')
productJ6 = Product.create(dispensary_id: 10, name: "Banana OG", brand: "Apothecary Genetics", price: 30.00, category: "Shatter", size: "per 1 g", url: 'images/products/KingsGardenBananaOG.png')

SelectElite5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/SelectElite.png')
productI1.photo.attach(io: SelectElite5, filename: 'SelectElite.png')
Releaf5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Releaf.png')
productI2.photo.attach(io: Releaf5, filename: 'Releaf.png')
icc5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/icc.png')
productI3.photo.attach(io: icc5, filename: 'icc.png')
smokiez5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/smokiez.png')
productI4.photo.attach(io: smokiez5, filename: 'smokiez.png')
theremedy5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/theremedy.png')
productI5.photo.attach(io: theremedy5, filename: 'theremedy.png')
Nuvata5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Nuvata.png')
productI6.photo.attach(io: Nuvata5, filename: 'Nuvata.png')

KnightsTemplar5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KnightsTemplar.png')
productJ1.photo.attach(io: KnightsTemplar5, filename: 'KnightsTemplar.png')
Canndescent5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Canndescent.png')
productJ2.photo.attach(io: Canndescent5, filename: 'Canndescent.png')
gelonade5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/gelonade.png')
productJ3.photo.attach(io: gelonade5, filename: 'gelonade.png')
AnimasValleyLiveResin5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/AnimasValleyLiveResin.png')
productJ4.photo.attach(io: AnimasValleyLiveResin5, filename: 'AnimasValleyLiveResin.png')
kanha5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/kanha.png')
productJ5.photo.attach(io: kanha5, filename: 'kanha.png')
KingsGardenBananaOG5 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KingsGardenBananaOG.png')
productJ6.photo.attach(io: KingsGardenBananaOG5, filename: 'KingsGardenBananaOG.png')


productK1 = Product.create(dispensary_id: 11, name: "Releaf Balm 3:1 CBD:THC 600mg", brand: "Papa & Barkley", price: 90.00, category: "Balms & Salves", size: "15mL", url: 'images/products/Releaf.png')
productK2 = Product.create(dispensary_id: 11, name: "Ice Cream Cake", brand: "Humboldt's Finest", price: 120.00, category: "Flower", size: "per 1/2 oz", url: 'images/products/icc.png')
productK3 = Product.create(dispensary_id: 11, name: "Sour Watermelon Fruit Chews", brand: "Smokiez Edibles", price: 16.00, category: "Edibles", size: "10 pieces per package", url: 'images/products/smokiez.png')
productK4 = Product.create(dispensary_id: 11, name: "The Remedy", brand: "Mary's Medicinals", price: 50.00, category: "Tincture", size: "60 servings in a 15mL bottle", url: 'images/products/theremedy.png')
productK5 = Product.create(dispensary_id: 11, name: "Full Mind - Strawberry", brand: "Nuvata", price: 40.00, category: "Disposable Vape Pen", size: "per 1/2 g", url: 'images/products/Nuvata.png')
productK6 = Product.create(dispensary_id: 11, name: "Original Glue #4", brand: "Select Elite", price: 30.00, category: "Cartridge", size: "per 1/2 g", url: 'images/products/SelectElite.png')

productL1 = Product.create(dispensary_id: 12, name: "Calm 101", brand: "Canndescent", price: 60.00, category: "Flower", size: "per 1/8 oz", url: 'images/products/Canndescent.png')
productL2 = Product.create(dispensary_id: 12, name: "Gelonade", brand: "Connected Cannabis Co.", price: 18.00, category: "Pre-Roll", size: "1g", url: 'images/products/gelonade.png')
productL3 = Product.create(dispensary_id: 12, name: "Animas Valley", brand: "Raw Garden", price: 35.00, category: "Live Resin", size: "per 1 g", url: 'images/products/AnimasValleyLiveResin.png')
productL4 = Product.create(dispensary_id: 12, name: "Pink Lemonade", brand: "Kanha", price: 14.00, category: "Gummies", size: "10 pieces x 10mg/gummy", url: 'images/products/kanha.png')
productL5 = Product.create(dispensary_id: 12, name: "Banana OG", brand: "Apothecary Genetics", price: 30.00, category: "Shatter", size: "per 1 g", url: 'images/products/KingsGardenBananaOG.png')
productL6 = Product.create(dispensary_id: 12, name: "Dark Heart Nursery", brand: "Knights Templar", price: 16.00, category: "Clone", size: "each", url: 'images/products/KnightsTemplar.png')

Releaf6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Releaf.png')
productK1.photo.attach(io: Releaf6, filename: 'Releaf.png')
icc6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/icc.png')
productK2.photo.attach(io: icc6, filename: 'icc.png')
smokiez6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/smokiez.png')
productK3.photo.attach(io: smokiez6, filename: 'smokiez.png')
theremedy6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/theremedy.png')
productK4.photo.attach(io: theremedy6, filename: 'theremedy.png')
Nuvata6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Nuvata.png')
productK5.photo.attach(io: Nuvata6, filename: 'Nuvata.png')
SelectElite6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/SelectElite.png')
productK6.photo.attach(io: SelectElite6, filename: 'SelectElite.png')

Canndescent6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/Canndescent.png')
productL1.photo.attach(io: Canndescent6, filename: 'Canndescent.png')
gelonade6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/gelonade.png')
productL2.photo.attach(io: gelonade6, filename: 'gelonade.png')
AnimasValleyLiveResin6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/AnimasValleyLiveResin.png')
productL3.photo.attach(io: AnimasValleyLiveResin6, filename: 'AnimasValleyLiveResin.png')
kanha6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/kanha.png')
productL4.photo.attach(io: kanha6, filename: 'kanha.png')
KingsGardenBananaOG6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KingsGardenBananaOG.png')
productL5.photo.attach(io: KingsGardenBananaOG6, filename: 'KingsGardenBananaOG.png')
KnightsTemplar6 = open('https://hash-maps-pro.s3.us-west-1.amazonaws.com/products/KnightsTemplar.png')
productL6.photo.attach(io: KnightsTemplar6, filename: 'KnightsTemplar.png')
